server:
  port: 8181
  
spring:
  datasource:
    url: jdbc:h2:mem:testdb

  kafka:   
    producer:
      acks: all
      retries: 5
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    bootstrap-servers:
    - localhost:19092
    - localhost:19093
    - localhost:19094

    consumer:
      group-id: delivery-service
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.DelegatingDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.kafka.serialization.selector.config: "commande:org.apache.kafka.common.serialization.StringDeserializer, position:org.springframework.kafka.support.serializer.JsonDeserializer"
    listener:
#      type: batch
      concurrency: 10
      client-id: delivery-service
      ack-mode: count
      ack-count: 500   
      idle-between-polls: 0

app:
  coursier-channel: 'coursiers'
  livraison-channel: 'livraisons'
