server:
  port: 8181
  
spring:
  datasource:
    url: jdbc:h2:mem:testdb

  kafka:   
    producer:
      acks: all
      retries: 5
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    bootstrap-servers:
    - localhost:19092
    - localhost:19093
    - localhost:19094
      
app:
  coursier-channel: 'coursiers'
  livraison-channel: 'livraisons'
