server:
  port: 8081

spring:
  jpa:
    show-sql: false
  datasource:
    url: jdbc:h2:mem:orderdb
    username: sa
  kafka:
    bootstrap-servers:
    - localhost:19092, localhost:19093, localhost:19094
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer 
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      transactionIdPrefix: "order-tx-"         

app:
  order-channel: 'orders'
  payment-in-channel: 'payments-in'
  payment-out-channel: 'payments-out'
  
logging:
  level:
    org.springframework.transaction: trace
    org.springframework.kafka.transaction: debug
